- sutakovNikitaBlankTemplate/App.js
- sutakovNikitaBlankTemplate/package-lock.json
- sutakovNikitaBlankTemplate/package.json
- sutakovNikitaBlankTemplate/screens/lab1.js
- sutakovNikitaBlankTemplate/screens/lab2.js
Выполнил вторую лабу: получаю через API погодные данные о городе, посредством ввода названия в TextInput
> lab2 get weather api completed

- sutakovNikitaBlankTemplate/App.js
- sutakovNikitaBlankTemplate/package-lock.json
- sutakovNikitaBlankTemplate/package.json
- sutakovNikitaBlankTemplate/screens/lab3.js
- Добавил файл lab3.js для реализации хука useMemo
- Модифицировал файл App.js, добавив отрисовку скрина lab3
- С помощью хука useEffect и axios-запроса получаю fakeStoreData со стороннего API, который содержит данные по товарам с фейкового интернет-магазина
- При изменении фильтров минимальной цены, максимальной цены и метода сортировки вызывается функция getFilteredItems, привязанная к хуку useMemo
- Для целесообразности работы хука useMemo добавил переключение темной темы экрана
> lab3 completed

- neustroevNurgun/App.js
- neustroevNurgun/package-lock.json
- neustroevNurgun/package.json
- neustroevNurgun/screens/lab1.js
- neustroevNurgun/screens/lab2.js
- Добавлен Tab navigation.
- Верхний текст случайного факта (на английском).
- Кнопка для получения другого случайного факта.
- Нижний текст сегодняшнего факта.
> neustroevNurgun - Lab 2 & navigator

- velievAzizagaFIIT21/screens/lab3.js
Добавил изменение цвета текста для показа работы useMemo
> velievAzizaga

- sutakovNikitaBlankTemplate/components/ThemedSafeAreaView.js
- sutakovNikitaBlankTemplate/hooks/useTheme.js
- sutakovNikitaBlankTemplate/package-lock.json
- sutakovNikitaBlankTemplate/package.json
- sutakovNikitaBlankTemplate/screens/lab1.js
- sutakovNikitaBlankTemplate/screens/lab2.js
- sutakovNikitaBlankTemplate/screens/lab3.js
- sutakovNikitaBlankTemplate/store/themeStore.js
- Добавил в проект менеджер состояний Zustand
- Реализовал переключение светлой/темной темы для всех экранов
- В папке store создал themeStore.js для хранения состояния темы в приложении
- В папке hooks создал кастомный хук useTheme, чтобы избежать повторения/переиспользования кода на различных экранах
- В папке components создал кастомный компонент ThemedSafeAreaView, чтобы избежать повторения/переиспользования кода на различных экранах
- Добавил переключение темной/светлой темы
- Задание стилей вынес в StyleSheet
- Заменил SafeAreaView на ThemedSafeAreaView
> Лабораторная работа №4

- sleptsovAnton/App.js
- sleptsovAnton/screens/lab3.js
Добавлена 3 лаба которая из бесплатного апи randomuser берет случайно сгенерированные данные людей. Допустим у нас компания, и я в ней могу добавлять, удалять и искать сотрудников
> 3 лаба слепцов антон

- nikulinMaksim-IVT-21-1/App.js
- nikulinMaksim-IVT-21-1/hooks/themeManager.js
- nikulinMaksim-IVT-21-1/package-lock.json
- nikulinMaksim-IVT-21-1/package.json
- nikulinMaksim-IVT-21-1/redux/store.js
- nikulinMaksim-IVT-21-1/redux/themeChange.js
- nikulinMaksim-IVT-21-1/screens/lab1.js
- nikulinMaksim-IVT-21-1/screens/lab2.js
- nikulinMaksim-IVT-21-1/screens/lab3.js
Использовал Redux для сохранения, изменения и использования state`а
> lab-4 nikulinMaksim

- sutakovNikitaBlankTemplate/README.md
Добавил ссылку в README на дизайн мобильного приложения в Figma
> figma link added

- potapovAndrey/lab1/lab1/app/index.tsx
- potapovAndrey/lab1/lab1/app/lab3.tsx
Создал массив данных **DATA** с 21 элементами. Также создал компонент Item, который отображает имя элемента.
Использовал **useMemo** для создания мемоизированной версии данных **memoizedData**, которая зависит от значения **count**. Когда **count** меняется, **memoizedData** также меняется. также использовал **React.memo** для создания мемоизированной версии компонента Item, чтобы избежать ненужных рендеров.
Когда рендерим список элементов использую **memoizedData** и **MemoizedItem** для оптимизации рендеринга. Это позволяет избежать ненужных рендеров и улучшает производительность приложения.
> Лаба 3 "UseMemo"

- tarasovRuslan/App.js
- tarasovRuslan/package-lock.json
- tarasovRuslan/package.json
- tarasovRuslan/screens/Lab1.js
- tarasovRuslan/screens/Lab2.js
- tarasovRuslan/screens/Lab3.js
- tarasovRuslan/store.js
Лабораторная 4: Добавил стейт-менеджер Redux и использовал его на все экраны.
Исправление лабораторной 3: добавлена принудительная перерисовка экрана с помощью состояния key.
> Лабораторная 4 + исправление лаб 3

- maximKharitonov/app/(tabs)/index.tsx
Добавлен функционал счетчика и кнопки сброса.
> 2 lab "use state"

- nikolaevEvgeniy-IVT-21-2/App.js
- nikolaevEvgeniy-IVT-21-2/Screens/Lab1.js
- nikolaevEvgeniy-IVT-21-2/Screens/Lab2.js
- nikolaevEvgeniy-IVT-21-2/store.js
- nikolaevEvgeniy-IVT-21-2/styles.js
Lab1: UseState
Добавлено:
Счетчик с вызовом задачи каждые 10 шагов.
Проверка правильности ответа для продолжения увеличения счетчика.
Использовано:
Хук useState для управления состояниями: счетчиком, вызовом задачи, состоянием ввода.
> добавил lab1

- gogolevAlexanderFIIT21/App.js
- gogolevAlexanderFIIT21/Screens/Lab4.js
- gogolevAlexanderFIIT21/Screens/Lab4_2.js
- gogolevAlexanderFIIT21/store/store.js
Lab4. В экране "Задачи" пользователь может добавить задачу, удалить её и отмечать задачу как завершенный или в процессе. Так же есть счетчик завершенных задач.
В экране "Завершенные задачи" показывает задачи, которые отмечены как завершенные из экрана задачи.
> сделал Lab4

- aisenSleptsov/slaian/App.js
- aisenSleptsov/slaian/layout/lab2.js
Компонент меняет фон на случайный цвет при нажатии
> выполнил lab2

- gavrilevAysien/App.js
- gavrilevAysien/package-lock.json
- gavrilevAysien/package.json
- gavrilevAysien/screens/lab1.js
- gavrilevAysien/screens/lab2.js
- gavrilevAysien/screens/lab3.js
- gavrilevAysien/store/themeStore.js
Добавил смену темы с помощью zustand и так же сверстал по фигме.
> Lab4 + verstka 

- maximKharitonov/app/(tabs)/_layout.tsx
- maximKharitonov/app/(tabs)/timer.tsx
- maximKharitonov/components/ui/IconSymbol.tsx
Добавил новый экран с таймером с использованием use effect: timer.tsx
До этого были добавлены два экрана:
1) Счетчик со сбросом с использованием use state
2) Экран с отображением погоды и кнопкой выбора города. Используется use memo + api
Также были затронуты файлы _layout.tsx и IconSymbol.tsx для добавления иконки
> lab 3 use effect

- sleptsovAnton/App.js
- sleptsovAnton/README.md
- sleptsovAnton/package-lock.json
- sleptsovAnton/package.json
- sleptsovAnton/screens/lab4_1.js
- sleptsovAnton/screens/lab4_2.js
- sleptsovAnton/store/zustand.js
я использовал zustand для создания менеджера задач. В 4.1 можно добавлять задачи, редактировать их и удалять, а в 4.2 завершать эти задачи
> Сделана лабораторная 4 и 5(фигма)

- chepalovNikolay/App.js
- chepalovNikolay/package-lock.json
- chepalovNikolay/package.json
- chepalovNikolay/screens/lab1.js
Сделал кнопку меняющая цвет фигуры
> Сделал лабу useState

- fedotovaAlina/App.js
- fedotovaAlina/screens/Lab1.js
Кнопка для изменения цвета фона
> Сделала useState

- bolshakovPetr/app/(tabs)/_layout.tsx
- bolshakovPetr/app/(tabs)/lab1.tsx
- bolshakovPetr/app/(tabs)/lab2.tsx
- bolshakovPetr/app/(tabs)/lab3.tsx
- bolshakovPetr/app/(tabs)/lab3_2.tsx
- bolshakovPetr/app/(tabs)/lab4.tsx
- bolshakovPetr/app/(tabs)/lab4_2.tsx
> bolshakovPetr_lab6_fixed

- fedotovaAlina/App.js
- fedotovaAlina/screens/Lab2.js
Сделала простой калькулятор, который прибавляет числа.
> Сделала useMemo

- potapovAndrey/lab1/lab1/app/_layout.tsx
- potapovAndrey/lab1/lab1/app/index.tsx
- potapovAndrey/lab1/lab1/app/lab1.tsx
- potapovAndrey/lab1/lab1/app/lab2.tsx
- potapovAndrey/lab1/lab1/app/lab3.tsx
- potapovAndrey/lab1/lab1/package-lock.json
- potapovAndrey/lab1/lab1/package.json
> Сделал лаб 6. Перенос figma

- chepalovNikolay/App.js
- chepalovNikolay/screens/lab2.js
useMemo с использованием API coindesk
> Сделал Лабу useMemo

- chepalovNikolay/App.js
- chepalovNikolay/screens/lab3.js
> Сделал третий экран

- popovAysenIVT-21-1/App.js
- popovAysenIVT-21-1/Readme.md
- popovAysenIVT-21-1/screen/lab1.js
- popovAysenIVT-21-1/screen/lab2.js
- popovAysenIVT-21-1/screen/lab3.js
> Lab-6 (Figma)
